# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_useremailaddress_confirmation_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='from user')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='to entity')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'entity likes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='entitylike',
            unique_together=set([('from_user', 'to_entity')]),
        ),
    ]
