# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitylike',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='to user'),
        ),
        migrations.AlterField(
            model_name='entitylike',
            name='to_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='to entity'),
        ),
        migrations.AlterUniqueTogether(
            name='entitylike',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
