# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='date_viewed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_from_user', to=settings.AUTH_USER_MODEL, verbose_name='from user'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_user', to=settings.AUTH_USER_MODEL, verbose_name='to user'),
        ),
    ]
