# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20170103_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitylike',
            name='to_entity',
        ),
        migrations.AlterField(
            model_name='entitylike',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='to user'),
        ),
    ]
