# Generated by Django 3.2.8 on 2021-10-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20200607_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
