# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20170103_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityLike',
            new_name='UserLike',
        ),
    ]
