# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composer_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='speedy_composer_site_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
