# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='ID contains illegal characters', regex='[0-9]')])),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'entity',
                'verbose_name': 'entity',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Entity')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=75, verbose_name='first name')),
                ('first_name_en', models.CharField(max_length=75, null=True, verbose_name='first name')),
                ('first_name_he', models.CharField(max_length=75, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=75, verbose_name='last name')),
                ('last_name_en', models.CharField(max_length=75, null=True, verbose_name='last name')),
                ('last_name_he', models.CharField(max_length=75, null=True, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.SmallIntegerField(choices=[(2, 'Male'), (1, 'Female'), (3, 'Other')], verbose_name='gender')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('profile_picture', models.ImageField(blank=True, upload_to='accounts/user/profile_picture/', verbose_name='profile picture')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('accounts.entity', models.Model),
        ),
    ]
