# Generated by Django 2.1.15 on 2020-01-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_en',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_he',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
    ]
