# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='indicates if a user has ever logged in to the site'),
        ),
    ]
