# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import speedy.net.accounts.managers
import speedy.net.uploads.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', speedy.net.accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='photo',
            field=speedy.net.uploads.fields.PhotoField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploads.Image', verbose_name='photo'),
        ),
    ]
