# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models

import speedy.net.accounts.managers


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', speedy.net.accounts.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
