# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 17:43
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_user_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserEmailAddress = apps.get_model('accounts', 'UserEmailAddress')
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        UserEmailAddress.objects.using(db_alias).create(
            user=user,
            email=user.email,
            is_primary=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20160607_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is confirmed')),
                ('is_primary', models.BooleanField(default=True, verbose_name='is primary')),
            ],
            options={
                'verbose_name_plural': 'email addresses',
                'verbose_name': 'email address',
            },
        ),
        migrations.AddField(
            model_name='useremailaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses',
                                    to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.RunPython(
            code=migrate_user_emails,
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
