# Generated by Django 3.0.6 on 2020-05-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0002_auto_20200103_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteprofile',
            options={'ordering': ('-last_visit', 'user_id'), 'verbose_name': 'Speedy Net Profile', 'verbose_name_plural': 'Speedy Net Profiles'},
        ),
    ]
