# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0002_auto_20170505_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='notify_on_message',
            field=models.PositiveIntegerField(choices=[(1, 'Notify me'), (0, "Don't notify me")], default=1, verbose_name='on new messages'),
        ),
    ]
