# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import speedy.net.accounts.managers
import speedy.net.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161021_1122'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', speedy.net.accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='access_dob_day_month',
            field=speedy.net.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=4, verbose_name='who can view my birth month and day'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='access_dob_year',
            field=speedy.net.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=4, verbose_name='who can view my birth year'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.CharField(error_messages={'unique': 'This username is already taken.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is already taken.'}, max_length=255, unique=True),
        ),
    ]
