# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 10:14
from __future__ import unicode_literals

from django.db import migrations
import speedy.net.accounts.managers
import speedy.net.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161103_1009'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', speedy.net.accounts.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='public_email',
        ),
        migrations.AddField(
            model_name='useremailaddress',
            name='access',
            field=speedy.net.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=1, verbose_name='who can see this email'),
        ),
    ]
