# Generated by Django 3.1.1 on 2021-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0003_auto_20200523_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='friends_count',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
