# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0003_auto_20170724_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='access_dob_day_month',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='access_dob_year',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='notify_on_message',
        ),
    ]
