# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160607_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailaddress',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=32, verbose_name='confirmation token'),
        ),
    ]
