# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0005_auto_20171003_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='speedy_net_site_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
