# Generated by Django 4.0.7 on 2022-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0005_auto_20210221_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='friends_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
