# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160608_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailaddress',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='is primary'),
        ),
    ]
