# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import speedy.net.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160608_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=False, verbose_name='indicates if a user has ever logged in to Speedy Net')),
                ('access_account', speedy.net.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (3, 'Me, my friends and friends of my friends'), (4, 'Anyone')], default=4, verbose_name='who can view my account')),
                ('public_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserEmailAddress', verbose_name='display email')),
            ],
            options={
                'verbose_name_plural': 'Speedy Net Profiles',
                'verbose_name': 'Speedy Net Profile',
            },
        ),
    ]
