# Generated by Django 4.1.9 on 2023-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0006_alter_siteprofile_friends_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_fr',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
    ]
