# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0006_auto_20180628_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
