# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_siteprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='public_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.UserEmailAddress', verbose_name='display email'),
        ),
    ]
