# Generated by Django 4.1.10 on 2023-07-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0007_siteprofile_number_of_friends_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_de',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_es',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_it',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_pt',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
    ]
