# Generated by Django 4.1.10 on 2023-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0008_siteprofile_number_of_friends_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_fi',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_ko',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_nl',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_friends_sv',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of friends on last user's visit"),
        ),
    ]
