# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160614_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='useremailaddress',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
