# Generated by Django 4.2.16 on 2024-10-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0009_siteprofile_number_of_friends_fi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofile',
            old_name='number_of_friends_en',
            new_name='number_of_friends',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_de',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_es',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_fi',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_fr',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_he',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_it',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_ko',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_nl',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_pt',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='number_of_friends_sv',
        ),
    ]
