# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160630_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='notify_on_message',
            field=models.PositiveIntegerField(choices=[(1, 'Notify'), (0, "Don't notify")], default=1, verbose_name='on new messages'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='indicates if a user has ever logged in to the site'),
        ),
    ]
