# Generated by Django 4.2.16 on 2024-10-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0010_rename_number_of_friends_en_siteprofile_number_of_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='number_of_friends',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Number of friends on last user's visit"),
        ),
    ]
