# Generated by Django 4.2.16 on 2024-10-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net_accounts', '0011_alter_siteprofile_number_of_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofile',
            old_name='friends_count',
            new_name='all_friends_count',
        ),
        migrations.RenameField(
            model_name='siteprofile',
            old_name='number_of_friends',
            new_name='speedy_net_friends_count',
        ),
    ]
