# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 09:28
from __future__ import unicode_literals

from django.db import migrations
import speedy.net.accounts.managers
import speedy.net.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20161116_0955'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', speedy.net.accounts.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='access_dob_day_month',
            field=speedy.net.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=1, verbose_name='who can view my birth month and day'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='access_dob_year',
            field=speedy.net.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=1, verbose_name='who can view my birth year'),
        ),
    ]
