# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 09:29
from __future__ import unicode_literals

from django.db import migrations
import speedy.net.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20161116_0928'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', speedy.net.accounts.managers.UserManager()),
            ],
        ),
    ]
