# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 17:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import speedy.net.uploads.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20160711_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='photo',
            field=speedy.net.uploads.fields.PhotoField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploads.Image', verbose_name='photo'),
        ),
    ]
