# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20160721_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailaddress',
            name='confirmation_sent',
            field=models.IntegerField(default=0, verbose_name='confirmation sent'),
        ),
    ]
