# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 10:54
from __future__ import unicode_literals

import random
import string

import re

import django.core.validators
from django.db import migrations, models


def create_random_username():
    return ''.join(random.choice(string.ascii_lowercase) for i in range(8))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_useremailaddress_confirmation_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='username',
            field=models.CharField(default=create_random_username, max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Username contains illegal characters.', regex='[a-z0-9]')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='ID contains illegal characters.', regex='[0-9]')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Slug contains illegal characters.', regex='[a-z0-9\\-]')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Other')], verbose_name='gender'),
        ),
    ]
