# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 12:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import speedy.core.models
import speedy.net.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20161117_0840'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', speedy.net.accounts.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=speedy.core.models.SmallUDIDField(db_index=True, default=speedy.core.models.generate_small_udid, max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='id contains illegal characters', regex='^[1-9][0-9]{14}$')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.CharField(error_messages={'unique': 'This username is already taken.'}, max_length=255, unique=True, verbose_name='username (slug)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is already taken.'}, max_length=255, unique=True, verbose_name='username'),
        ),
    ]
