# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20161123_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('id',), 'verbose_name': 'entity', 'verbose_name_plural': 'entity'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-last_login', 'id'), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
