# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 16:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20160811_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Slug contains illegal characters.', regex='[a-z0-9\\-]')]),
        ),
    ]
