# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 11:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import speedy.core.models
import speedy.net.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20160922_1611'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', speedy.net.accounts.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=speedy.core.models.UDIDField(db_index=True, max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='ID contains illegal characters.', regex='[0-9]')], verbose_name='ID'),
        ),
    ]
