# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 17:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import speedy.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20161125_1300'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=speedy.core.models.SmallUDIDField(db_index=True, max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='id contains illegal characters', regex='^[1-9][0-9]{14}$')], verbose_name='ID'),
        ),
    ]
