# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 11:36
from __future__ import unicode_literals

from datetime import datetime, timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20161125_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='last_visit',
            field=models.DateTimeField(auto_now_add=True, default=datetime(1970, 1, 1, tzinfo=timezone.utc), verbose_name='last visit'),
            preserve_default=False,
        ),
    ]
