# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_siteprofile_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserEmailAddress',
        ),
    ]
