# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 16:36
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import speedy.core.models
import speedy.net.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20161201_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailAddress',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', speedy.core.models.RegularUDIDField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='id contains illegal characters', regex='^[1-9][0-9]{19}$')], verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is confirmed')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('confirmation_token', models.CharField(blank=True, max_length=32, verbose_name='confirmation token')),
                ('confirmation_sent', models.IntegerField(default=0, verbose_name='confirmation sent')),
                ('access', speedy.net.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=1, verbose_name='who can see this email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'email addresses',
                'verbose_name': 'email address',
            },
        ),
    ]
