# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_useremailaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremailaddress',
            options={'ordering': ('date_created', 'id'), 'verbose_name': 'email address', 'verbose_name_plural': 'email addresses'},
        ),
    ]
