# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20161202_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.SmallIntegerField(choices=[(0, 'Please select...'), (1, 'Vegan'), (2, 'Vegeterian'), (3, 'Carnist')], default=0, verbose_name='diet'),
        ),
    ]
