# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20161125_1900'),
        ('im', '0005_auto_20161125_1900'),
        ('feedback', '0001_initial'),
        ('accounts', '0025_auto_20161213_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedentity',
            name='entity_ptr',
        ),
        migrations.DeleteModel(
            name='NamedEntity',
        ),
    ]
