# Generated by Django 3.0.6 on 2020-05-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteprofile',
            options={'ordering': ('-last_visit', 'user_id'), 'verbose_name': 'Speedy Mail Profile', 'verbose_name_plural': 'Speedy Mail Profiles'},
        ),
    ]
