# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_accounts', '0003_auto_20180628_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteprofile',
            options={'verbose_name': 'Speedy Mail Software Profile', 'verbose_name_plural': 'Speedy Mail Software Profiles'},
        ),
    ]
