# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_accounts', '0004_auto_20181225_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteprofile',
            options={'verbose_name': 'Speedy Mail Profile', 'verbose_name_plural': 'Speedy Mail Profiles'},
        ),
    ]
