# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_accounts', '0005_auto_20190110_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
