# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import speedy.core.uploads.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('uploads', '0001_initial'),
        ('accounts_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='photo',
            field=speedy.core.uploads.fields.PhotoField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploads.Image', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
