from django.conf import settings as django_settings

if (django_settings.TESTS):
    from speedy.core.base.test.mixins import TestCaseMixin

    class SpeedyCoreAdminLanguageMixin(TestCaseMixin):
        def set_up(self):
            super().set_up()

            _permission_denied_h1_dict = {'en': 'Permission Denied', 'fr': 'Permission Refusée', 'de': 'Erlaubnisse Abgelehnt', 'es': 'Permiso Denegado', 'pt': 'Permissão Recusada', 'it': 'Autorizzazione Negata', 'nl': 'Geen Toestemming', 'ja': 'アクセスが拒否されました', 'ru': 'Доступ запрещен', 'zh': '权限被拒绝', 'pl': 'Brak uprawnień', 'fa': 'دسترسی رد شد', 'he': 'ההרשאה נדחתה', 'ko': '권한 거부됨', 'ar': 'تم رفض الإذن', 'az': 'İcazə rədd edildi', 'id': 'Izin ditolak', 'uk': 'Доступ заборонено', 'tr': 'İzin reddedildi', 'vi': 'Quyền truy cập bị từ chối', 'cs': 'Přístup odepřen', 'sv': 'Tillträde Nekat', 'fi': 'Lupa Kielletty', 'hu': 'Hozzáférés megtagadva', 'th': 'ปฏิเสธการเข้าถึง', 'el': 'Δεν επιτρέπεται η πρόσβαση', 'ms': 'Kebenaran ditolak', 'sr': 'Приступ одбијен', 'ro': 'Permisiune refuzată', 'bn': 'অনুমতি প্রত্যাখ্যাত', 'ca': 'Permís denegat', 'no': 'Tilgang nektet', 'bg': 'Достъпът е отказан', 'da': 'Adgang nægtet', 'sk': 'Prístup odmietnutý', 'hi': 'अनुमति अस्वीकृत', 'et': 'Juurdepääs keelatud', 'hr': 'Pristup odbijen'}
            _speedy_is_sorry_but_this_page_is_private_alert_dict = {'en': 'Speedy is sorry, but this page is private.', 'fr': 'Speedy est désolée, mais cette page est privée.', 'de': 'Speedy tut es leid, aber diese Seite ist privat.', 'es': 'Speedy lo siente, pero esta página es privada.', 'pt': 'A Speedy lamenta, mas esta página é privativa.', 'it': 'Speedy è spiacente, ma questa pagina è privata.', 'nl': 'Het spijt Speedy, maar deze pagina is privé.', 'ja': 'Speedy 様 申し訳ございませんが、このページは非公開です。', 'ru': 'Спиди извините, но эта страница является частной. Speedy', 'zh': 'Speedy 很抱歉，但此頁面是私人的。', 'pl': 'Speedy przepraszamy, ale ta strona jest prywatna.', 'fa': 'Speedy متاسفم، اما این صفحه خصوصی است.', 'he': 'ספידי מצטערת, אבל הדף הזה פרטי.', 'ko': 'Speedy에서 죄송하게 생각합니다만, 이 페이지는 비공개입니다.', 'ar': 'سبيدي آسف، ولكن هذه الصفحة خاصة. Speedy', 'az': 'Speedy üzr istəyir, lakin bu səhifə məxfidir.', 'id': 'Speedy minta maaf, tapi halaman ini bersifat pribadi.', 'uk': 'Speedy вибачте, але ця сторінка приватна.', 'tr': 'Speedy kusura bakma ama bu sayfa özeldir.', 'vi': 'Speedy rất tiếc, nhưng trang này là riêng tư.', 'cs': 'Speedy je mi líto, ale tato stránka je soukromá.', 'sv': 'Speedy beklagar, men den här sidan är privat.', 'fi': 'Speedy pahoittelee, mutta tämä sivu on yksityinen.', 'hu': 'Speedy elnézést kér, de ez az oldal privát.', 'th': 'Speedy ขออภัย แต่เพจนี้เป็นเพจส่วนตัว', 'el': 'Speedy συγγνώμη, αλλά αυτή η σελίδα είναι ιδιωτική.', 'ms': 'Speedy minta maaf, tetapi halaman ini adalah peribadi.', 'sr': 'Спееди је жао, али ова страница је приватна. Speedy', 'ro': 'Speedy îmi pare rău, dar această pagină este privată.', 'bn': 'দ্রুত দুঃখিত, কিন্তু এই পৃষ্ঠাটি ব্যক্তিগত. Speedy', 'ca': 'Speedy ho sento, però aquesta pàgina és privada.', 'no': 'Speedy beklager, men denne siden er privat.', 'bg': 'Спиди съжалява, но тази страница е лична. Speedy', 'da': 'Speedy beklager, men denne side er privat.', 'sk': 'Speedy prepáč, ale táto stránka je súkromná.', 'hi': 'स्पीडी को खेद है, लेकिन यह पेज निजी है। Speedy', 'et': 'Vabandage Speedy, kuid see leht on privaatne.', 'hr': 'Speedy se ispričava, ali ova stranica je privatna.'}
            _speedy_net_profiles_dict = {'en': 'Speedy Net Profiles', 'fr': 'Profils Speedy Net', 'de': 'Speedy Net-Profile', 'es': 'Perfiles de Speedy Net', 'pt': 'Perfis do Speedy Net', 'it': 'Profili Speedy Net', 'nl': 'Speedy Net Profielen', 'ja': 'Speedy Net Profiles', 'ru': 'Speedy Net Profiles', 'zh': 'Speedy Net Profiles', 'pl': 'Speedy Net Profiles', 'fa': 'Speedy Net Profiles', 'he': 'פרופילים ספידי נט', 'ko': 'Speedy Net 프로필', 'ar': 'Speedy Net Profiles', 'az': 'Speedy Net profilləri', 'id': 'Speedy Net Profiles', 'uk': 'Speedy Net Profiles', 'tr': 'Speedy Net Profiles', 'vi': 'Speedy Net Profiles', 'cs': 'Speedy Net Profiles', 'sv': 'Speedy Net-profiler', 'fi': 'Speedy Net Profiilit', 'hu': 'Speedy Net Profiles', 'th': 'Speedy Net Profiles', 'el': 'Speedy Net Profiles', 'ms': 'Speedy Net Profiles', 'sr': 'Speedy Net Profiles', 'ro': 'Speedy Net Profiles', 'bn': 'Speedy Net Profiles', 'ca': 'Speedy Net Profiles', 'no': 'Speedy Net Profiles', 'bg': 'Speedy Net Profiles', 'da': 'Speedy Net Profiles', 'sk': 'Speedy Net Profiles', 'hi': 'Speedy Net Profiles', 'et': 'Speedy Net Profiles', 'hr': 'Speedy Net Profiles'}
            _speedy_match_profiles_dict = {'en': 'Speedy Match Profiles', 'fr': 'Profils Speedy Match', 'de': 'Speedy Match-Profile', 'es': 'Perfiles de Speedy Match', 'pt': 'Perfis do Speedy Match', 'it': 'Profili Speedy Match', 'nl': 'Speedy Match Profielen', 'ja': 'Speedy Match Profiles', 'ru': 'Speedy Match Profiles', 'zh': 'Speedy Match Profiles', 'pl': 'Speedy Match Profiles', 'fa': 'Speedy Match Profiles', 'he': "פרופילים ספידי מץ'", 'ko': 'Speedy Match 프로필', 'ar': 'Speedy Match Profiles', 'az': 'Speedy Match profilləri', 'id': 'Speedy Match Profiles', 'uk': 'Speedy Match Profiles', 'tr': 'Speedy Match Profiles', 'vi': 'Speedy Match Profiles', 'cs': 'Speedy Match Profiles', 'sv': 'Speedy Match-profiler', 'fi': 'Speedy Match Profiilit', 'hu': 'Speedy Match Profiles', 'th': 'Speedy Match Profiles', 'el': 'Speedy Match Profiles', 'ms': 'Speedy Match Profiles', 'sr': 'Speedy Match Profiles', 'ro': 'Speedy Match Profiles', 'bn': 'Speedy Match Profiles', 'ca': 'Speedy Match Profiles', 'no': 'Speedy Match Profiles', 'bg': 'Speedy Match Profiles', 'da': 'Speedy Match Profiles', 'sk': 'Speedy Match Profiles', 'hi': 'Speedy Match Profiles', 'et': 'Speedy Match Profiles', 'hr': 'Speedy Match Profiles'}

            self._permission_denied_h1 = _permission_denied_h1_dict[self.language_code]
            self._speedy_is_sorry_but_this_page_is_private_alert = _speedy_is_sorry_but_this_page_is_private_alert_dict[self.language_code]
            self._speedy_net_profiles = _speedy_net_profiles_dict[self.language_code]
            self._speedy_match_profiles = _speedy_match_profiles_dict[self.language_code]


