from django.conf import settings as django_settings

if (django_settings.TESTS):
    from speedy.core.base.test.mixins import SpeedyCoreBaseLanguageMixin, TestCaseMixin


    class SpeedyCoreMessagesLanguageMixin(SpeedyCoreBaseLanguageMixin, TestCaseMixin):
        def _ensure_this_value_has_at_most_max_length_characters_errors_dict_by_value_length(self, value_length):
            return {'text': [self._ensure_this_value_has_at_most_max_length_characters_error_message_by_max_length_and_value_length(max_length=50000, value_length=value_length)]}

        def set_up(self):
            super().set_up()

            _you_have_a_new_message_on_speedy_net_subject_dict = {'en': 'You have a new message on Speedy Net', 'fr': 'Vous avez un nouveau message sur Speedy Net', 'de': 'Sie haben eine neue Mitteilung erhalten auf Speedy Net', 'es': 'Tienes un nuevo mensaje en Speedy Net', 'pt': 'Tu tens uma nova mensagem em Speedy Net', 'it': 'Hai un nuovo messaggio su Speedy Net', 'nl': 'Je hebt een nieuw bericht ingeschakeld Speedy Net', 'ja': 'Speedy Net に新しいメッセージがあります', 'ru': 'У вас новое сообщение в Speedy Net', 'zh': '您在 Speedy Net 上有一条新消息', 'pl': 'Masz nową wiadomość w Speedy Net', 'fa': 'شما یک پیام جدید در Speedy Net دارید', 'he': 'יש לך הודעה חדשה בספידי נט', 'ko': 'Speedy Net에 새 메시지가 있습니다', 'ar': 'لديك رسالة جديدة على Speedy Net', 'az': 'Speedy Net-də yeni mesajınız var', 'id': 'Anda memiliki pesan baru di Speedy Net', 'uk': 'У вас нове повідомлення у Speedy Net', 'tr': 'Speedy Net üzerinde yeni bir mesajınız var', 'vi': 'Bạn có một tin nhắn mới trên Speedy Net', 'cs': 'Na platformě Speedy Net máte novou zprávu', 'sv': 'Du har ett nytt meddelande på Speedy Net', 'fi': 'Sinulla on uusi viesti Speedy Net', 'hu': 'Új üzeneted érkezett a Speedy Net oldalon', 'th': 'คุณมีข้อความใหม่บน Speedy Net', 'el': 'Έχετε νέο μήνυμα στο Speedy Net', 'ms': 'Anda mempunyai mesej baharu di Speedy Net', 'sr': 'Имате нову поруку на Speedy Net', 'ro': 'Ai un mesaj nou pe Speedy Net', 'bn': 'Speedy Net-এ আপনার একটি নতুন বার্তা আছে', 'ca': 'Tens un missatge nou a Speedy Net', 'no': 'Du har en ny melding på Speedy Net', 'bg': 'Имате ново съобщение в Speedy Net', 'da': 'Du har en ny besked på Speedy Net', 'sk': 'Máte novú správu na Speedy Net', 'hi': 'Speedy Net पर आपका एक नया संदेश है', 'et': 'Sul on Speedy Net platvormil uus sõnum', 'hr': 'Imate novu poruku na platformi Speedy Net'}
            _you_have_a_new_message_on_speedy_match_subject_dict = {'en': 'You have a new message on Speedy Match', 'fr': 'Vous avez un nouveau message sur Speedy Match', 'de': 'Sie haben eine neue Mitteilung erhalten auf Speedy Match', 'es': 'Tienes un nuevo mensaje en Speedy Match', 'pt': 'Tu tens uma nova mensagem em Speedy Match', 'it': 'Hai un nuovo messaggio su Speedy Match', 'nl': 'Je hebt een nieuw bericht ingeschakeld Speedy Match', 'ja': 'Speedy Match に新しいメッセージがあります', 'ru': 'У вас новое сообщение в Speedy Match', 'zh': '您在 Speedy Match 上有一条新消息', 'pl': 'Masz nową wiadomość w Speedy Match', 'fa': 'شما یک پیام جدید در Speedy Match دارید', 'he': "יש לך הודעה חדשה בספידי מץ'", 'ko': 'Speedy Match에 새 메시지가 있습니다', 'ar': 'لديك رسالة جديدة على Speedy Match', 'az': 'Speedy Match-də yeni mesajınız var', 'id': 'Anda memiliki pesan baru di Speedy Match', 'uk': 'У вас нове повідомлення у Speedy Match', 'tr': 'Speedy Match üzerinde yeni bir mesajınız var', 'vi': 'Bạn có một tin nhắn mới trên Speedy Match', 'cs': 'Na platformě Speedy Match máte novou zprávu', 'sv': 'Du har ett nytt meddelande på Speedy Match', 'fi': 'Sinulla on uusi viesti Speedy Match', 'hu': 'Új üzeneted érkezett a Speedy Match oldalon', 'th': 'คุณมีข้อความใหม่บน Speedy Match', 'el': 'Έχετε νέο μήνυμα στο Speedy Match', 'ms': 'Anda mempunyai mesej baharu di Speedy Match', 'sr': 'Имате нову поруку на Speedy Match', 'ro': 'Ai un mesaj nou pe Speedy Match', 'bn': 'Speedy Match-এ আপনার একটি নতুন বার্তা আছে', 'ca': 'Tens un missatge nou a Speedy Match', 'no': 'Du har en ny melding på Speedy Match', 'bg': 'Имате ново съобщение в Speedy Match', 'da': 'Du har en ny besked på Speedy Match', 'sk': 'Máte novú správu na Speedy Match', 'hi': 'Speedy Match पर आपका एक नया संदेश है', 'et': 'Sul on Speedy Match platvormil uus sõnum', 'hr': 'Imate novu poruku na platformi Speedy Match'}

            self._you_have_a_new_message_on_speedy_net_subject = _you_have_a_new_message_on_speedy_net_subject_dict[self.language_code]
            self._you_have_a_new_message_on_speedy_match_subject = _you_have_a_new_message_on_speedy_match_subject_dict[self.language_code]


