# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 15:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import speedy.core.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20170117_1516'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', speedy.core.base.models.RegularUDIDField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='id contains illegal characters', regex='^[1-9][0-9]{19}$')], verbose_name='ID')),
                ('is_group', models.BooleanField(default=False, verbose_name='is group chat')),
                ('ent1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='participant 1')),
                ('ent2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='participant 2')),
                ('group', models.ManyToManyField(to='accounts.Entity', verbose_name='participants')),
            ],
            options={
                'ordering': ('-last_message__date_created', '-date_updated'),
                'verbose_name_plural': 'chat',
                'verbose_name': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', speedy.core.base.models.RegularUDIDField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='id contains illegal characters', regex='^[1-9][0-9]{19}$')], verbose_name='ID')),
                ('text', models.TextField(verbose_name='message')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.Chat', verbose_name='chat')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Entity', verbose_name='sender')),
            ],
            options={
                'get_latest_by': 'date_created',
                'ordering': ('-date_created',),
                'verbose_name_plural': 'messages',
                'verbose_name': 'message',
            },
        ),
        migrations.CreateModel(
            name='ReadMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='im.Chat', verbose_name='chat')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='entity')),
            ],
            options={
                'get_latest_by': 'date_created',
                'verbose_name_plural': 'read marks',
                'verbose_name': 'read mark',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='im.Message', verbose_name='last message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='site'),
        ),
    ]
