# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='ent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.Entity', verbose_name='participant 1'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='ent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.Entity', verbose_name='participant 2'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='im.Message', verbose_name='last message'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='site'),
        ),
    ]
