# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0002_auto_20180627_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='ent1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.Entity', verbose_name='participant 1'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='ent2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.Entity', verbose_name='participant 2'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='im.Message', verbose_name='last message'),
        ),
    ]
