# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0003_auto_20180810_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='ent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.Entity', verbose_name='participant 1'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='ent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.Entity', verbose_name='participant 2'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='im.Message', verbose_name='last message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.Chat', verbose_name='chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Entity', verbose_name='sender'),
        ),
    ]
