# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0005_auto_20181017_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-last_message__date_created', '-date_updated'), 'verbose_name': 'chat', 'verbose_name_plural': 'chats'},
        ),
    ]
