# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-06 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='file size'),
        ),
    ]
