# Generated by Django 3.0.6 on 2020-06-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-date_created',), 'verbose_name': 'file', 'verbose_name_plural': 'uploaded files'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-date_created',), 'verbose_name': 'images', 'verbose_name_plural': 'uploaded images'},
        ),
    ]
