# Generated by Django 3.2.8 on 2021-11-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20201209_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-date_created',), 'verbose_name': 'uploaded file', 'verbose_name_plural': 'uploaded files'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-date_created',), 'verbose_name': 'uploaded image', 'verbose_name_plural': 'uploaded images'},
        ),
    ]
