# Generated by Django 4.1.13 on 2024-01-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20211123_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='speedy_image_moderation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Speedy image moderation time'),
        ),
    ]
