# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160630_1956'),
        ('im', '0002_chat_last_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='im.Chat', verbose_name='chat')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='entity')),
            ],
            options={
                'verbose_name': 'read mark',
                'verbose_name_plural': 'read marks',
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'date_created', 'ordering': ('-date_created',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
