# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0003_auto_20161123_1431'),
        ('im', '0003_auto_20161123_1300'),
    ]

    operations = [
    ]
