# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 17:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import speedy.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0004_merge_20161125_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=speedy.core.models.RegularUDIDField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='id contains illegal characters', regex='^[1-9][0-9]{19}$')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=speedy.core.models.RegularUDIDField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='id contains illegal characters', regex='^[1-9][0-9]{19}$')], verbose_name='ID'),
        ),
    ]
