# Generated by Django 2.1.15 on 2019-12-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='ent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.Entity', verbose_name='participant 1'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='ent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.Entity', verbose_name='participant 2'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Entity', verbose_name='sender'),
        ),
    ]
