# Generated by Django 2.1.15 on 2020-01-06 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_messages', '0002_auto_20191229_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=50000, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='message'),
        ),
    ]
