# Generated by Django 3.0.6 on 2020-06-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_messages', '0003_auto_20200106_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readmark',
            options={'get_latest_by': 'date_created', 'ordering': ('-date_created',), 'verbose_name': 'read mark', 'verbose_name_plural': 'read marks'},
        ),
    ]
