# Generated by Django 3.1.1 on 2020-12-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201010_0757'),
        ('core_messages', '0005_auto_20201009_0920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readmark',
            unique_together={('entity', 'chat')},
        ),
    ]
