# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import speedy.core.models
import speedy.net.uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', speedy.core.models.UDIDField(db_index=True, default=speedy.core.models.generate_id, max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='id contains illegal characters', regex='[0-9]')], verbose_name='ID')),
                ('file', models.FileField(upload_to=speedy.net.uploads.models.uuid_dir, verbose_name='file')),
                ('is_stored', models.BooleanField(default=False, verbose_name='is stored')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='file_size')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'uploaded files',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uploads.File')),
            ],
            options={
                'verbose_name': 'images',
                'verbose_name_plural': 'uploaded images',
            },
            bases=('uploads.file',),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Entity', verbose_name='owner'),
        ),
    ]
