# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_auto_20160711_1708'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='your name')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='your email')),
                ('type', models.PositiveIntegerField(verbose_name='type')),
                ('text', models.TextField(verbose_name='text')),
                ('report_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='accounts.Entity', verbose_name='reported entity')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'ordering': ('-date_created',),
                'verbose_name_plural': 'feedbacks',
                'verbose_name': 'feedback',
            },
        ),
    ]
