# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='your message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Feedback'), (1, 'Abuse (User)'), (2, 'Abuse (Photo)')], verbose_name='type'),
        ),
    ]
