# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
        ('feedback', '0002_auto_20160724_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='report_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='uploads.File', verbose_name='reported photo'),
        ),
    ]
