# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('blockee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts_core.Entity', verbose_name='blocked user')),
                ('blocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts_core.Entity', verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'user blocks',
                'verbose_name': 'block',
            },
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([('blocker', 'blockee')]),
        ),
    ]
