# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([]),
        ),
    ]
