# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_rename_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='blocked user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='blocker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='user'),
            preserve_default=False,
        ),
    ]
