# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180322_1252'),
        ('blocks', '0003_remove_all_block_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='blocked user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='blocker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Entity', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='block',
            name='blockee',
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([('blocker', 'blocked')]),
        ),
    ]
