# Generated by Django 4.0.6 on 2022-07-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210802_1412'),
        ('blocks', '0003_alter_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_entities+', to='accounts.entity', verbose_name='blocked user'),
        ),
        migrations.AlterField(
            model_name='block',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_entities+', to='accounts.entity', verbose_name='user'),
        ),
    ]
