# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 11:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.CharField(db_index=True, max_length=256, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='username contains illegal characters', regex='[\\s\\-_a-zA-Z0-9]')])),
                ('slug', models.SlugField(unique=True)),
                ('model_type', models.SmallIntegerField(choices=[(1, 'USER'), (2, 'USER PROFILE'), (3, 'PAGE')], null=True)),
            ],
            options={
                'verbose_name_plural': 'Identities',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('identity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Identity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='UserEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Email addresses',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('opened', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(1916, 1, 7), null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Other')], default=3)),
                ('diet', models.SmallIntegerField(choices=[(1, 'Eat all'), (2, 'Vegeterian'), (3, 'Vegan')], default=1)),
                ('profile_picture', models.ImageField(blank=True, default='default_profile_pic.png', upload_to='user_pictures/')),
                ('field_privacy', django.contrib.postgres.fields.jsonb.JSONField(default={'date_of_birth': 1, 'diet': 1, 'email': 1, 'first_name': 1, 'gender': 1, 'last_name': 1})),
                ('identity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Identity')),
                ('password_reset_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_user', to='base.Token')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sent_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='base.UserProfile'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='base.UserProfile'),
        ),
        migrations.AddField(
            model_name='useremailaddress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.UserProfile'),
        ),
        migrations.AddField(
            model_name='useremailaddress',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Token'),
        ),
    ]
