# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190713_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedUsername',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Entity')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.entity',),
        ),
    ]
