# Generated by Django 2.0.13 on 2019-10-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190812_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_he',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
