# Generated by Django 2.1.15 on 2020-01-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_has_confirmed_email'),
    ]

    operations = [
    ]
