# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180322_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Vegan (eats only plants and fungi)'), (2, "Vegetarian (doesn't eat fish and meat)"), (3, 'Carnist (eats animals)')], default=0, verbose_name='diet'),
        ),
    ]
