# Generated by Django 2.1.15 on 2020-01-06 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_has_confirmed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedusername',
            name='description',
            field=models.TextField(blank=True, max_length=50000, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='description'),
        ),
    ]
