# Generated by Django 3.0.6 on 2020-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200121_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_he',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
    ]
