# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 12:26
from __future__ import unicode_literals

from django.db import migrations

from speedy.core.base.utils import string_is_not_empty


def forwards_func(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        save = False
        for fn in ['first_name_en', 'first_name_he']:
            if (not(string_is_not_empty(getattr(user, fn)))):
                setattr(user, fn, getattr(user, 'first_name'))
                save = True
        for fn in ['last_name_en', 'last_name_he']:
            if (not(string_is_not_empty(getattr(user, fn)))):
                setattr(user, fn, getattr(user, 'last_name'))
                save = True
        if save:
            user.save()


def backwards_func(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        setattr(user, 'first_name', getattr(user, 'first_name_en'))
        setattr(user, 'last_name', getattr(user, 'last_name_en'))
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181017_1956'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
