# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_update_names_20190204_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(max_length=75, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_he',
            field=models.CharField(max_length=75, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(max_length=75, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_he',
            field=models.CharField(max_length=75, verbose_name='last name'),
        ),
    ]
