# Generated by Django 3.0.6 on 2020-05-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200514_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-speedy_net_site_profile__last_visit', 'id'), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
