# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 12:26
from __future__ import unicode_literals

from django.db import migrations

from speedy.core.base.utils import string_is_not_empty


def forwards_func(apps, schema_editor):
    from speedy.core.accounts.models import User as User1
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        user.validators = {}
        user.relationship_status = User1.RELATIONSHIP_STATUS_UNKNOWN
        user.save()
        print (user.pk, user.username, user.relationship_status)


def backwards_func(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        print (user.pk, user.username, user.relationship_status)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190731_1043'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
