# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190204_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='city or locality'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_he',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='city or locality'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'In a relationship'), (5, 'In an open relationship'), (6, "It's complicated"), (7, 'Separated'), (8, 'Married')], default=0, verbose_name='marital status'),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking_status',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'No'), (2, 'Sometimes'), (3, 'Yes')], default=0, verbose_name='smoking status'),
        ),
    ]
