# Generated by Django 3.1.1 on 2020-09-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200607_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_he',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_he',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
    ]
