# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import speedy.core.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_relationship_status_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='smoking_status',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Not smoking'), (2, 'Smoking sometimes'), (3, 'Smoking')], default=0, verbose_name='smoking status'),
        ),
        migrations.AlterField(
            model_name='useremailaddress',
            name='access',
            field=speedy.core.accounts.models.UserAccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=1, verbose_name='Who can see this email'),
        ),
    ]
