# Generated by Django 3.1.1 on 2020-09-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200922_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_he',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
    ]
