# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190731_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='smoking_status',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Not smoking'), (2, 'Smoking occasionally'), (3, 'Smoking')], default=0, verbose_name='smoking status'),
        ),
    ]
