# Generated by Django 3.1.1 on 2020-10-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200930_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('-date_created',), 'verbose_name': 'entity', 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='reservedusername',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-speedy_net_site_profile__last_visit',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='useremailaddress',
            options={'ordering': ('-date_created',), 'verbose_name': 'email address', 'verbose_name_plural': 'email addresses'},
        ),
    ]
