# Generated by Django 3.1.12 on 2021-08-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210622_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip_address_used',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ip_address_used_date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ip_address_used_ipapi_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last IP address used https://ipapi.com/ time'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ip_address_used_raw_ipapi_results',
            field=models.JSONField(blank=True, null=True, verbose_name='Last IP address used raw https://ipapi.com/ results'),
        ),
    ]
