# Generated by Django 4.1.9 on 2023-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210802_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_fr',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_fr',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_fr',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
    ]
