# Generated by Django 4.1.10 on 2023-07-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_city_fr_user_first_name_fr_user_last_name_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_es',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_it',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_pt',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_de',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_de',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_es',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_es',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_it',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_it',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_pt',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_pt',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql='UPDATE "accounts_user" SET "first_name_de" = first_name_en, "last_name_de" = last_name_en, "first_name_es" = first_name_en, "last_name_es" = last_name_en, "first_name_it" = first_name_en, "last_name_it" = last_name_en, "first_name_pt" = first_name_en, "last_name_pt" = last_name_en;',
            reverse_sql='',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_de',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_es',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_it',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_pt',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_de',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_es',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_it',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_pt',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
    ]
