# Generated by Django 4.1.10 on 2023-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_city_de_user_city_es_user_city_it_user_city_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_fi',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_ko',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_nl',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_sv',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_fi',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_fi',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ko',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ko',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_nl',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_nl',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_sv',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_sv',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql='UPDATE "accounts_user" SET "first_name_fi" = first_name_en, "last_name_fi" = last_name_en, "first_name_ko" = first_name_en, "last_name_ko" = last_name_en, "first_name_nl" = first_name_en, "last_name_nl" = last_name_en, "first_name_sv" = first_name_en, "last_name_sv" = last_name_en;',
            reverse_sql='',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_fi',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_ko',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_nl',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_sv',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_fi',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_ko',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_nl',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_sv',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
    ]
