# Generated by Django 4.1.13 on 2024-02-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
