# Generated by Django 4.2.11 on 2024-04-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_is_deleted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip_address_used_original_ipapi_call',
            field=models.BooleanField(default=False),
        ),
    ]
