# Generated by Django 4.2.13 on 2024-06-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_last_ip_address_used_original_ipapi_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_to_change_date_of_birth_unlimited_times',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_date_of_birth_changes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
