# Generated by Django 6.0.6 on 2026-07-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_allowed_to_change_date_of_birth_unlimited_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_ar',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_bg',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_bn',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_ca',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_cs',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_da',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_el',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_et',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_hi',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_hr',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_hu',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_ja',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_ms',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_no',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_pl',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_ro',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_sk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_sr',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_th',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_tr',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_vi',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_zh',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ar',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_bg',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_bn',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ca',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_cs',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_da',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_el',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_et',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_fa',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_hi',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_hr',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_hu',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_id',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ja',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ms',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_no',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_pl',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ro',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ru',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_sk',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_sr',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_th',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_tr',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_uk',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_vi',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_zh',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ar',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_bg',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_bn',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ca',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_cs',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_da',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_el',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_et',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_fa',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_hi',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_hr',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_hu',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_id',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ja',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ms',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_no',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_pl',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ro',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ru',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_sk',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_sr',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_th',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_tr',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_uk',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_vi',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_zh',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql='UPDATE "accounts_user" SET '
                '"first_name_ar" = first_name_en, "last_name_ar" = last_name_en, '
                '"first_name_bg" = first_name_en, "last_name_bg" = last_name_en, '
                '"first_name_bn" = first_name_en, "last_name_bn" = last_name_en, '
                '"first_name_ca" = first_name_en, "last_name_ca" = last_name_en, '
                '"first_name_cs" = first_name_en, "last_name_cs" = last_name_en, '
                '"first_name_da" = first_name_en, "last_name_da" = last_name_en, '
                '"first_name_el" = first_name_en, "last_name_el" = last_name_en, '
                '"first_name_et" = first_name_en, "last_name_et" = last_name_en, '
                '"first_name_fa" = first_name_en, "last_name_fa" = last_name_en, '
                '"first_name_hi" = first_name_en, "last_name_hi" = last_name_en, '
                '"first_name_hr" = first_name_en, "last_name_hr" = last_name_en, '
                '"first_name_hu" = first_name_en, "last_name_hu" = last_name_en, '
                '"first_name_id" = first_name_en, "last_name_id" = last_name_en, '
                '"first_name_ja" = first_name_en, "last_name_ja" = last_name_en, '
                '"first_name_ms" = first_name_en, "last_name_ms" = last_name_en, '
                '"first_name_no" = first_name_en, "last_name_no" = last_name_en, '
                '"first_name_pl" = first_name_en, "last_name_pl" = last_name_en, '
                '"first_name_ro" = first_name_en, "last_name_ro" = last_name_en, '
                '"first_name_ru" = first_name_en, "last_name_ru" = last_name_en, '
                '"first_name_sk" = first_name_en, "last_name_sk" = last_name_en, '
                '"first_name_sr" = first_name_en, "last_name_sr" = last_name_en, '
                '"first_name_th" = first_name_en, "last_name_th" = last_name_en, '
                '"first_name_tr" = first_name_en, "last_name_tr" = last_name_en, '
                '"first_name_uk" = first_name_en, "last_name_uk" = last_name_en, '
                '"first_name_vi" = first_name_en, "last_name_vi" = last_name_en, '
                '"first_name_zh" = first_name_en, "last_name_zh" = last_name_en '
                ';',
            reverse_sql='',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_ar',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_bg',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_bn',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_ca',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_cs',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_da',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_el',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_et',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_fa',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_hi',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_hr',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_hu',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_id',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_ja',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_ms',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_no',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_pl',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_ro',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_ru',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_sk',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_sr',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_th',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_tr',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_uk',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_vi',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_zh',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_ar',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_bg',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_bn',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_ca',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_cs',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_da',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_el',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_et',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_fa',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_hi',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_hr',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_hu',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_id',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_ja',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_ms',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_no',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_pl',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_ro',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_ru',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_sk',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_sr',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_th',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_tr',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_uk',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_vi',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_zh',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
    ]
