# Generated by Django 6.0.8 on 2026-09-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_city_ar_user_city_bg_user_city_bn_user_city_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_az',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_az',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_az',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql='UPDATE "accounts_user" SET '
                '"first_name_az" = first_name_en, "last_name_az" = last_name_en '
                ';',
            reverse_sql='',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_az',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_az',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
    ]
