# Generated by Django 6.0.8 on 2026-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_city_az_user_first_name_az_user_last_name_az'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_eu',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_hy',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_lt',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_lv',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_sl',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_ta',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_uz',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_zh_yue',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Where do I live?'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_eu',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_hy',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_lt',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_lv',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_sl',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ta',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_uz',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_zh_yue',
            field=models.CharField(
                default=None, max_length=150, verbose_name='first name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_eu',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_hy',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_lt',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_lv',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_sl',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ta',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_uz',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_zh_yue',
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name='last name',
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql='UPDATE "accounts_user" SET '
                '"first_name_eu" = first_name_en, "last_name_eu" = last_name_en, '
                '"first_name_hy" = first_name_en, "last_name_hy" = last_name_en, '
                '"first_name_lt" = first_name_en, "last_name_lt" = last_name_en, '
                '"first_name_lv" = first_name_en, "last_name_lv" = last_name_en, '
                '"first_name_sl" = first_name_en, "last_name_sl" = last_name_en, '
                '"first_name_ta" = first_name_en, "last_name_ta" = last_name_en, '
                '"first_name_uz" = first_name_en, "last_name_uz" = last_name_en, '
                '"first_name_zh_yue" = first_name_en, "last_name_zh_yue" = last_name_en '
                ';',
            reverse_sql='',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_eu',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_hy',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_lt',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_lv',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_sl',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_ta',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_uz',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_zh_yue',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_eu',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_hy',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_lt',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_lv',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_sl',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_ta',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_uz',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_zh_yue',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='last name'),
        ),
    ]
