# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import speedy.core.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='your name')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='your email')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Feedback'), (1, 'Abuse (User)'), (2, 'Abuse (Photo)')], verbose_name='type')),
                ('text', models.TextField(verbose_name='your message')),
                ('report_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='accounts.Entity', verbose_name='reported entity')),
                ('report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='uploads.File', verbose_name='reported photo')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
                'ordering': ('-date_created',),
            },
            bases=(speedy.core.base.models.ValidateModelMixin, models.Model),
        ),
    ]
