# Generated by Django 2.1.15 on 2020-01-06 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_by_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=50000, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='your message'),
        ),
    ]
