# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_by_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
    ]
