# Generated by Django 2.1.15 on 2020-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_by_form', '0002_auto_20200106_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Feedback'), (1, 'Abuse (User)'), (2, 'Abuse (Photo)')], verbose_name='type'),
        ),
    ]
