# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 13:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import speedy.core.base.models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_visit', models.DateTimeField(auto_now_add=True, verbose_name='last visit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='speedy_match_site_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('notify_on_like', models.PositiveIntegerField(choices=[(1, 'Notify me'), (0, "Don't notify me")], default=1, verbose_name='on new likes')),
                ('active_languages', models.TextField(blank=True, verbose_name='active languages')),
                ('height', models.SmallIntegerField(blank=True, help_text='cm', null=True, verbose_name='height')),
                ('profile_description_en', models.TextField(blank=True, null=True, verbose_name='Few words about me')),
                ('profile_description_he', models.TextField(blank=True, null=True, verbose_name='Few words about me')),
                ('children_en', models.TextField(blank=True, null=True, verbose_name='Do you have children? How many?')),
                ('children_he', models.TextField(blank=True, null=True, verbose_name='Do you have children? How many?')),
                ('more_children_en', models.TextField(blank=True, null=True, verbose_name='Do you want (more) children?')),
                ('more_children_he', models.TextField(blank=True, null=True, verbose_name='Do you want (more) children?')),
                ('match_description_en', models.TextField(blank=True, null=True, verbose_name='My ideal match')),
                ('match_description_he', models.TextField(blank=True, null=True, verbose_name='My ideal match')),
                ('gender_to_match', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=speedy.match.accounts.models.SiteProfile.gender_to_match_default, null=True, size=3, verbose_name='Gender')),
                ('min_age_match', models.SmallIntegerField(default=0, verbose_name='minimal age to match')),
                ('max_age_match', models.SmallIntegerField(default=180, verbose_name='maximal age to match')),
                ('diet_match', django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.diet_match_default, verbose_name='diet match')),
                ('smoking_status_match', django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.smoking_status_match_default, verbose_name='smoking status match')),
                ('marital_status_match', django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.relationship_status_match_default, verbose_name='marital status match')),
                ('activation_step_en', models.PositiveSmallIntegerField(default=2)),
                ('activation_step_he', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Speedy Match Profile',
                'verbose_name_plural': 'Speedy Match Profiles',
            },
            bases=(speedy.core.base.models.ValidateModelMixin, models.Model),
        ),
    ]
