# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import speedy.net.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_auto_20161103_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_dob_day_month', speedy.net.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=4, verbose_name='who can view my birth month and day')),
                ('access_dob_year', speedy.net.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=4, verbose_name='who can view my birth year')),
                ('notify_on_message', models.PositiveIntegerField(choices=[(1, 'Notify'), (0, "Don't notify")], default=1, verbose_name='on new messages')),
                ('notify_on_like', models.PositiveIntegerField(choices=[(1, 'Notify'), (0, "Don't notify")], default=1, verbose_name='on new likes')),
                ('active_languages', models.TextField(blank=True, verbose_name='active languages')),
            ],
            options={
                'verbose_name': 'Speedy Match Profile',
                'verbose_name_plural': 'Speedy Match Profiles',
            },
        ),
    ]
