# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20160614_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=False, verbose_name='indicates if a user has ever logged in to Speedy Net')),
                ('public_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.UserEmailAddress', verbose_name='display email')),
            ],
            options={
                'verbose_name': 'Speedy Net Profile',
                'verbose_name_plural': 'Speedy Net Profiles',
            },
        ),
    ]
