# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 16:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='active_languages',
            field=models.TextField(blank=True, verbose_name='Active languages'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='diet_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.diet_match_default, verbose_name='Diet match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='gender_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=speedy.match.accounts.models.SiteProfile.gender_to_match_default, null=True, size=3, verbose_name='Gender to match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='height',
            field=models.SmallIntegerField(blank=True, help_text='cm', null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_status_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.relationship_status_match_default, verbose_name='Marital status match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='max_age_match',
            field=models.SmallIntegerField(default=180, verbose_name='Maximal age to match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='min_age_match',
            field=models.SmallIntegerField(default=0, verbose_name='Minimal age to match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='notify_on_like',
            field=models.PositiveIntegerField(choices=[(1, 'Notify me'), (0, "Don't notify me")], default=1, verbose_name='On new likes'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking_status_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.smoking_status_match_default, verbose_name='Smoking status match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='speedy_match_site_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
