# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='notify_on_message',
            field=models.PositiveIntegerField(choices=[(1, 'Notify'), (0, "Don't notify")], default=1, verbose_name='on new messages'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='indicates if a user has ever logged in to the site'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='public_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.UserEmailAddress', verbose_name='public email'),
        ),
    ]
