# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='children',
            field=models.TextField(null=True, verbose_name='Do you have children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='diet',
            field=models.SmallIntegerField(choices=[(1, 'Vegan (eats only plants and fungi)'), (2, "Vegetarian (doesn't eat fish and meat)"), (3, 'Carnist (eats animals)')], null=True, verbose_name='Diet'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='height',
            field=models.SmallIntegerField(null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(0, 'Single'), (1, 'Divorced'), (2, 'Widowed'), (3, 'In a relatioship'), (4, 'In an open relationship'), (5, 'Complicated'), (6, 'Separated'), (7, 'Married')], null=True, verbose_name='Marital status'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='max_age_match',
            field=models.SmallIntegerField(null=True, verbose_name='Minial age to match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='men_to_match',
            field=models.NullBooleanField(verbose_name='Interested in men'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='min_age_match',
            field=models.SmallIntegerField(null=True, verbose_name='Minial age to match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children',
            field=models.TextField(null=True, verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='other_to_match',
            field=models.NullBooleanField(default=True, verbose_name='Interested in others'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_desription',
            field=models.TextField(null=True, verbose_name='About myself'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='smoking',
            field=models.SmallIntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Sometimes')], null=True, verbose_name='Smoking'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='women_to_match',
            field=models.NullBooleanField(default=True, verbose_name='Interested in women'),
        ),
    ]
