# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='access_dob_day_month',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='access_dob_year',
        ),
    ]
