# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 15:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='gender_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=speedy.match.accounts.models.SiteProfile.gender_to_match_default, null=True, size=3, verbose_name='Gender to match'),
        ),
    ]
