# Generated by Django 2.1.14 on 2019-11-27 02:34

from django.db import migrations, models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='max_age_to_match',
            field=models.SmallIntegerField(default=speedy.match.accounts.models.SiteProfile.max_age_to_match_default, verbose_name='Maximal age to match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='min_age_to_match',
            field=models.SmallIntegerField(default=speedy.match.accounts.models.SiteProfile.min_age_to_match_default, verbose_name='Minimal age to match'),
        ),
    ]
