# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='children',
            field=models.TextField(null=True, verbose_name='do you have children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='diet_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='diet match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='gender_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=[1, 2, 3], size=3),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='height',
            field=models.SmallIntegerField(null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='marital match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'In a relatioship'), (5, 'In an open relationship'), (6, 'Complicated'), (7, 'Separated'), (8, 'Married')], default=0, verbose_name='marital status'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='max_age_match',
            field=models.SmallIntegerField(default=180, verbose_name='maximal age to match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='min_age_match',
            field=models.SmallIntegerField(default=0, verbose_name='minial age to match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children',
            field=models.TextField(null=True, verbose_name='do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_desription',
            field=models.TextField(null=True, verbose_name='about myself'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='smoking',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Sometimes')], default=0, verbose_name='smoking'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='smoking_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='smoking match'),
        ),
    ]
