# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0002_auto_20170301_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='diet_carnist_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Carnist match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='diet_vegan_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Vegan match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='diet_vegetarian_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Vegetarian match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_complicated_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='I an complicated relationship match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_divorced_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Divorced match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_married_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Married match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_open_relationship_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='I an open relationship match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_relationship_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='I an relationship match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_separated_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Separated match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_single_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Singles match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_widowed_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Widowed match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='smoking_no_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='No smoking match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='smoking_sometimes_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Sometimes smoking match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='smoking_yes_match',
            field=models.SmallIntegerField(choices=[(0, '0 stars'), (1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='Smoking match'),
        ),
    ]
