# Generated by Django 2.1.15 on 2020-01-06 09:19

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0002_auto_20191127_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='active_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=speedy.match.accounts.models.SiteProfile.active_languages_default, null=True, size=2, verbose_name='Active languages'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='children_en',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='children_he',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='match_description_en',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='match_description_he',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='more_children_en',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='more_children_he',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_description_en',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_description_he',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
    ]
