# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0002_auto_20170302_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'In a relatioship'), (5, 'In an open relationship'), (6, "It's complicated"), (7, 'Separated'), (8, 'Married')], default=0, verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking',
            field=models.SmallIntegerField(choices=[(1, 'No'), (2, 'Yes'), (3, 'Sometimes')], default=0, verbose_name='smoking'),
        ),
    ]
