# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0002_auto_20160710_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='notify_on_like',
            field=models.PositiveIntegerField(choices=[(1, 'Notify'), (0, "Don't notify")], default=1, verbose_name='on new likes'),
        ),
    ]
