# Generated by Django 2.1.15 on 2020-01-06 11:19

import django.contrib.postgres.fields
from django.db import migrations, models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0003_auto_20200106_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='active_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], max_length=2), blank=True, default=speedy.match.accounts.models.SiteProfile.active_languages_default, null=True, size=2, verbose_name='Active languages'),
        ),
    ]
