# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0003_auto_20170302_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofile',
            old_name='profile_desription',
            new_name='profile_description',
        ),
    ]
