# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0003_siteprofile_notify_on_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteprofile',
            options={'verbose_name': 'Speedy Match Profile', 'verbose_name_plural': 'Speedy Match Profiles'},
        ),
    ]
