# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 09:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0003_auto_20170301_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='diet_carnist_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='diet_vegan_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='diet_vegetarian_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='marital_complicated_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='marital_divorced_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='marital_married_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='marital_open_relationship_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='marital_relationship_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='marital_separated_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='marital_single_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='marital_widowed_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='smoking_no_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='smoking_sometimes_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='smoking_yes_match',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='diet_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Diet match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Marital match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='smoking_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Smoking match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'In a relatioship'), (5, 'In an open relationship'), (6, 'Complicated'), (7, 'Separated'), (8, 'Married')], null=True, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Sometimes')], null=True, verbose_name='Smoking'),
        ),
    ]
