# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0004_auto_20170323_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='children_en',
            field=models.TextField(null=True, verbose_name='do you have children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_he',
            field=models.TextField(null=True, verbose_name='do you have children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='city_en',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='city_he',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_en',
            field=models.TextField(null=True, verbose_name='do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_he',
            field=models.TextField(null=True, verbose_name='do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_en',
            field=models.TextField(null=True, verbose_name='about myself'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_he',
            field=models.TextField(null=True, verbose_name='about myself'),
        ),
    ]
