# Generated by Django 2.1.15 on 2020-01-06 16:38

import django.contrib.postgres.fields
from django.db import migrations, models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0004_auto_20200106_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='diet_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(choices=[(1, 'Vegan (eats only plants and fungi)'), (2, "Vegetarian (doesn't eat fish and meat)"), (3, 'Carnist (eats animals)')]), blank=True, default=speedy.match.accounts.models.SiteProfile.diet_to_match_default, null=True, size=3, verbose_name='Diet to match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='gender_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Other')]), blank=True, default=speedy.match.accounts.models.SiteProfile.gender_to_match_default, null=True, size=3, verbose_name='Gender to match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='relationship_status_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'In a relationship'), (5, 'In an open relationship'), (6, "It's complicated"), (7, 'Separated'), (8, 'Engaged'), (9, 'Married')]), blank=True, default=speedy.match.accounts.models.SiteProfile.relationship_status_to_match_default, null=True, size=9, verbose_name='Relationship status to match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking_status_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(choices=[(1, 'Not smoking'), (2, 'Smoking occasionally'), (3, 'Smoking')]), blank=True, default=speedy.match.accounts.models.SiteProfile.smoking_status_to_match_default, null=True, size=3, verbose_name='Smoking status to match'),
        ),
    ]
