# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0005_auto_20170323_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description',
            field=models.TextField(null=True, verbose_name=''),
        ),
    ]
