# Generated by Django 2.1.15 on 2020-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0005_auto_20200106_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='not_allowed_to_use_speedy_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='notify_on_like',
            field=models.SmallIntegerField(choices=[(1, 'Notify me'), (0, "Don't notify me")], default=1, verbose_name='On new likes'),
        ),
    ]
