# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 12:26
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    from speedy.core.accounts.models import User
    SpeedyMatchSiteProfile = apps.get_model("match_accounts", "SiteProfile")
    for speedy_match_profile in SpeedyMatchSiteProfile.objects.all():
        speedy_match_profile.diet_to_match = [diet for diet in User.DIET_VALID_VALUES if (speedy_match_profile.diet_match[str(diet)] > 0)]
        speedy_match_profile.smoking_status_to_match = [smoking_status for smoking_status in User.SMOKING_STATUS_VALID_VALUES if (speedy_match_profile.smoking_status_match[str(smoking_status)] > 0)]
        speedy_match_profile.relationship_status_to_match = [relationship_status for relationship_status in User.RELATIONSHIP_STATUS_VALID_VALUES if (speedy_match_profile.relationship_status_match[str(relationship_status)] > 0)]
        speedy_match_profile.save()
        print (speedy_match_profile.pk)


def backwards_func(apps, schema_editor):
    SpeedyMatchSiteProfile = apps.get_model("match_accounts", "SiteProfile")
    for speedy_match_profile in SpeedyMatchSiteProfile.objects.all():
        print (speedy_match_profile.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0006_auto_20190803_1327'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
