# Generated by Django 3.0.6 on 2020-05-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0006_auto_20200121_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteprofile',
            options={'ordering': ('-last_visit', 'user_id'), 'verbose_name': 'Speedy Match Profile', 'verbose_name_plural': 'Speedy Match Profiles'},
        ),
    ]
