# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0006_auto_20170329_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='max_height_match',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='maximal height to match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='min_height_match',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='minimal height to match'),
        ),
    ]
