# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-03 14:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0007_new_fields_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='active_languages_1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=speedy.match.accounts.models.SiteProfile.active_languages_default, null=True, size=2, verbose_name='Active languages'),
        ),
    ]
