# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0007_auto_20170329_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='max_height_match',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='min_height_match',
        ),
    ]
