# Generated by Django 3.1 on 2020-08-04 11:53

from django.db import migrations, models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0007_auto_20200523_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='diet_match',
            field=models.JSONField(default=speedy.match.accounts.models.SiteProfile.diet_match_default, verbose_name='Diet match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='relationship_status_match',
            field=models.JSONField(default=speedy.match.accounts.models.SiteProfile.relationship_status_match_default, verbose_name='Relationship status match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking_status_match',
            field=models.JSONField(default=speedy.match.accounts.models.SiteProfile.smoking_status_match_default, verbose_name='Smoking status match'),
        ),
    ]
