# Generated by Django 3.1.1 on 2020-12-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0008_auto_20200804_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='profile_picture_months_offset',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
