# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-03 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0009_active_languages_change_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='active_languages',
        ),
    ]
