# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 09:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0009_auto_20170329_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='diet_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 5, 2: 5, 3: 5}, verbose_name='diet match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='gender_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=[1, 2, 3], size=3, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5}, verbose_name='marital match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'In a relatioship'), (5, 'In an open relationship'), (6, "It's complicated"), (7, 'Separated'), (8, 'Married')], default=0, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='match_description',
            field=models.TextField(null=True, verbose_name='My ideal match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='match_description_en',
            field=models.TextField(null=True, verbose_name='My ideal match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='match_description_he',
            field=models.TextField(null=True, verbose_name='My ideal match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_description',
            field=models.TextField(null=True, verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_description_en',
            field=models.TextField(null=True, verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_description_he',
            field=models.TextField(null=True, verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 5, 2: 5, 3: 5}, verbose_name='smoking match'),
        ),
    ]
