# Generated by Django 3.1.6 on 2021-02-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0010_siteprofile_likes_to_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='likes_to_user_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
