# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-03 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0010_remove_siteprofile_active_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofile',
            old_name='active_languages_1',
            new_name='active_languages',
        ),
    ]
