# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 06:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0010_auto_20170405_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='marital_match',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='marital_status_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5}, verbose_name='marital status match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='gender_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=[], size=3, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'In a relatioship'), (5, 'In an open relationship'), (6, "It's complicated"), (7, 'Separated'), (8, 'Married')], default=0, verbose_name='marital status'),
        ),
    ]
