# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0011_auto_20190803_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='activation_step_en',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='activation_step_he',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
    ]
