# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-07 11:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0011_auto_20170505_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='children',
            field=models.TextField(null=True, verbose_name='Do you have children? How many?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='children_en',
            field=models.TextField(null=True, verbose_name='Do you have children? How many?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='children_he',
            field=models.TextField(null=True, verbose_name='Do you have children? How many?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='city or locality'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='city_en',
            field=models.CharField(max_length=255, null=True, verbose_name='city or locality'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='city_he',
            field=models.CharField(max_length=255, null=True, verbose_name='city or locality'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='more_children',
            field=models.TextField(null=True, verbose_name='Do you want (more) children?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='more_children_en',
            field=models.TextField(null=True, verbose_name='Do you want (more) children?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='more_children_he',
            field=models.TextField(null=True, verbose_name='Do you want (more) children?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking',
            field=models.SmallIntegerField(choices=[(1, 'No'), (2, 'Yes'), (3, 'Sometimes')], default=0, verbose_name='smoking status'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 5, 2: 5, 3: 5}, verbose_name='smoking status match'),
        ),
    ]
