# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import speedy.match.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0012_auto_20170507_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='height',
            field=models.SmallIntegerField(null=True, validators=[speedy.match.accounts.validators.validate_height], verbose_name='height'),
        ),
    ]
