# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0012_auto_20190809_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_en',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_he',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
    ]
