# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 15:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import speedy.match.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0013_auto_20170517_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='children',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_children], verbose_name='Do you have children? How many?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='children_en',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_children], verbose_name='Do you have children? How many?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='children_he',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_children], verbose_name='Do you have children? How many?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='city',
            field=models.CharField(max_length=255, null=True, validators=[speedy.match.accounts.validators.validate_city], verbose_name='city or locality'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='city_en',
            field=models.CharField(max_length=255, null=True, validators=[speedy.match.accounts.validators.validate_city], verbose_name='city or locality'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='city_he',
            field=models.CharField(max_length=255, null=True, validators=[speedy.match.accounts.validators.validate_city], verbose_name='city or locality'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='diet_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 5, 2: 5, 3: 5}, validators=[speedy.match.accounts.validators.validate_diet_match], verbose_name='diet match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='gender_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=[], size=3, validators=[speedy.match.accounts.validators.validate_gender_to_match], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'In a relatioship'), (5, 'In an open relationship'), (6, "It's complicated"), (7, 'Separated'), (8, 'Married')], default=0, validators=[speedy.match.accounts.validators.validate_marital_status], verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_status_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5}, validators=[speedy.match.accounts.validators.validate_marital_status_match], verbose_name='marital status match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='match_description',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_match_description], verbose_name='My ideal match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='match_description_en',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_match_description], verbose_name='My ideal match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='match_description_he',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_match_description], verbose_name='My ideal match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='max_age_match',
            field=models.SmallIntegerField(default=180, validators=[speedy.match.accounts.validators.validate_max_age_match], verbose_name='maximal age to match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='min_age_match',
            field=models.SmallIntegerField(default=0, validators=[speedy.match.accounts.validators.validate_min_age_match], verbose_name='minimal age to match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='more_children',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_more_children], verbose_name='Do you want (more) children?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='more_children_en',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_more_children], verbose_name='Do you want (more) children?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='more_children_he',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_more_children], verbose_name='Do you want (more) children?'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_description',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_profile_description], verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_description_en',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_profile_description], verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_description_he',
            field=models.TextField(null=True, validators=[speedy.match.accounts.validators.validate_profile_description], verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking',
            field=models.SmallIntegerField(choices=[(1, 'No'), (2, 'Yes'), (3, 'Sometimes')], default=0, validators=[speedy.match.accounts.validators.validate_smoking], verbose_name='smoking status'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 5, 2: 5, 3: 5}, validators=[speedy.match.accounts.validators.validate_smoking_match], verbose_name='smoking status match'),
        ),
    ]
