# Generated by Django 4.1.9 on 2023-06-10 10:35

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0013_alter_siteprofile_likes_to_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_fr',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_fr',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_fr',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_fr',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_fr',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_fr',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='active_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('he', 'Hebrew')], max_length=2), blank=True, default=speedy.match.accounts.models.SiteProfile.active_languages_default, null=True, size=3, verbose_name='Active languages'),
        ),
    ]
