# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import speedy.core.accounts.models
import speedy.match.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0014_auto_20170517_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='access_dob_day_month',
            field=speedy.core.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=1, verbose_name='who can view my birth month and day'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='access_dob_year',
            field=speedy.core.accounts.models.AccessField(choices=[(1, 'Only me'), (2, 'Me and my friends'), (4, 'Anyone')], default=1, verbose_name='who can view my birth year'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='height',
            field=models.SmallIntegerField(null=True, validators=[speedy.match.accounts.validators.validate_height], verbose_name='height cm'),
        ),
    ]
