# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import speedy.match.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0015_auto_20170620_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='height',
            field=models.SmallIntegerField(help_text='cm', null=True, validators=[speedy.match.accounts.validators.validate_height], verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='notify_on_like',
            field=models.PositiveIntegerField(choices=[(1, 'Notify me'), (0, "Don't notify me")], default=1, verbose_name='on new likes'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='notify_on_message',
            field=models.PositiveIntegerField(choices=[(1, 'Notify me'), (0, "Don't notify me")], default=1, verbose_name='on new messages'),
        ),
    ]
