# Generated by Django 4.1.10 on 2023-07-05 07:59

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0015_siteprofile_activation_step_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_fi',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_ko',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_nl',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_sv',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_fi',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_ko',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_nl',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_sv',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_fi',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_ko',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_nl',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_sv',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_fi',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_ko',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_nl',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_sv',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_fi',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_ko',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_nl',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_sv',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_fi',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_ko',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_nl',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_sv',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='active_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('it', 'Italian'), ('nl', 'Dutch'), ('sv', 'Swedish'), ('ko', 'Korean'), ('fi', 'Finnish'), ('he', 'Hebrew')], max_length=2), blank=True, default=speedy.match.accounts.models.SiteProfile.active_languages_default, null=True, size=11, verbose_name='Active languages'),
        ),
    ]
