# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0017_increase_activation_step'),
        ('match_accounts', '0017_auto_20170727_2009'),
    ]

    operations = [
    ]
