# Generated by Django 6.0.8 on 2026-09-02 02:45

import django.contrib.postgres.fields
import django.core.validators
import speedy.match.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0017_siteprofile_activation_step_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_az',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_az',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_az',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_az',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_az',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_az',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='active_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('it', 'Italian'), ('nl', 'Dutch'), ('ja', 'Japanese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('pl', 'Polish'), ('fa', 'Persian'), ('he', 'Hebrew'), ('ko', 'Korean'), ('ar', 'Arabic'), ('id', 'Indonesian'), ('uk', 'Ukrainian'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('cs', 'Czech'), ('sv', 'Swedish'), ('fi', 'Finnish'), ('hu', 'Hungarian'), ('th', 'Thai'), ('el', 'Greek'), ('ms', 'Malay'), ('sr', 'Serbian'), ('ro', 'Romanian'), ('bn', 'Bengali'), ('ca', 'Catalan'), ('no', 'Norwegian (Bokmål)'), ('bg', 'Bulgarian'), ('da', 'Danish'), ('sk', 'Slovak'), ('hi', 'Hindi'), ('et', 'Estonian'), ('hr', 'Croatian'), ('az', 'Azerbaijani')], max_length=2), blank=True, default=speedy.match.accounts.models.SiteProfile.active_languages_default, null=True, size=38, verbose_name='Active languages'),
        ),
    ]
