# Generated by Django 6.0.8 on 2026-09-23 15:24

import django.contrib.postgres.fields
import django.core.validators
import speedy.match.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0018_siteprofile_activation_step_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_eu',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_hy',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_lt',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_lv',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_sl',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_ta',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_uz',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='activation_step_zh_yue',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Activation step'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_eu',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_hy',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_lt',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_lv',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_sl',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_ta',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_uz',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='children_zh_yue',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you have children? How many?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_eu',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_hy',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_lt',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_lv',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_sl',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_ta',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_uz',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='match_description_zh_yue',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='My ideal match'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_eu',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_hy',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_lt',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_lv',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_sl',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_ta',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_uz',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='more_children_zh_yue',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Do you want (more) children?'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_eu',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_hy',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_lt',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_lv',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_sl',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_ta',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_uz',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_matches_zh_yue',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Number of matches on last user's search"),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_eu',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_hy',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_lt',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_lv',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_sl',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_ta',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_uz',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_description_zh_yue',
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50000)], verbose_name='Few words about me'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='active_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('it', 'Italian'), ('nl', 'Dutch'), ('ja', 'Japanese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('pl', 'Polish'), ('fa', 'Persian'), ('he', 'Hebrew'), ('ko', 'Korean'), ('ar', 'Arabic'), ('id', 'Indonesian'), ('uk', 'Ukrainian'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('cs', 'Czech'), ('sv', 'Swedish'), ('fi', 'Finnish'), ('hu', 'Hungarian'), ('th', 'Thai'), ('el', 'Greek'), ('ms', 'Malay'), ('sr', 'Serbian'), ('ro', 'Romanian'), ('bn', 'Bengali'), ('ca', 'Catalan'), ('no', 'Norwegian (Bokmål)'), ('bg', 'Bulgarian'), ('da', 'Danish'), ('sk', 'Slovak'), ('hi', 'Hindi'), ('et', 'Estonian'), ('hr', 'Croatian'), ('az', 'Azerbaijani'), ('zh-yue', 'Cantonese'), ('lt', 'Lithuanian'), ('sl', 'Slovenian'), ('eu', 'Basque'), ('hy', 'Armenian'), ('uz', 'Uzbek'), ('ta', 'Tamil'), ('lv', 'Latvian')], max_length=10), blank=True, default=speedy.match.accounts.models.SiteProfile.active_languages_default, null=True, size=46, verbose_name='Active languages'),
        ),
    ]
