# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0018_merge_20170728_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='activation_step',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
