# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 20:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import speedy.match.accounts.models
import speedy.match.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0021_auto_20180628_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='diet_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.diet_match_default, validators=[speedy.match.accounts.validators.validate_diet_match], verbose_name='diet match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='gender_to_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=speedy.match.accounts.models.SiteProfile.gender_to_match_default, size=3, validators=[speedy.match.accounts.validators.validate_gender_to_match], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_status_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.marital_status_match_default, validators=[speedy.match.accounts.validators.validate_marital_status_match], verbose_name='marital status match'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.smoking_match_default, validators=[speedy.match.accounts.validators.validate_smoking_match], verbose_name='smoking status match'),
        ),
    ]
