# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 20:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import speedy.match.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0025_auto_20180811_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='smoking_status_match',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=speedy.match.accounts.models.SiteProfile.smoking_status_match_default, verbose_name='smoking status match'),
        ),
    ]
