# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0026_auto_20180811_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='children',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='match_description',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='more_children',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='profile_description',
        ),
    ]
