# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_accounts', '0028_auto_20190709_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'In a relationship'), (5, 'In an open relationship'), (6, "It's complicated"), (7, 'Separated'), (8, 'Married')], default=0, verbose_name='marital status'),
        ),
    ]
